name: ashkan
version: 0.1.0.0
maintainer: "ashkan.kh.nazary@gmail.com"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/vulkan#readme>

dependencies:
  - base >= 4.7 && < 5
  - vulkan
  - vulkan-utils
  - bytestring
  - vector
  - sdl2
  - managed
  - mtl
  - extra
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wambiguous-fields
  # - -dynamic
  # - -dynload deploy
  # - -optl-Wl,-rpath,'$ORIGIN'
  - -optl-Wl,-rpath,/usr/local/lib
# - -optl

# library:
#   source-dirs: src

executables:
  ashkan:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    # dependencies:
    # - vulkan2

  ptr:
    main: Main.hs
    source-dirs: magic
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N