name: Vulkan2DEngine
version: 0.1.0
maintainer: "ashkan.kh.nazary@gmail.com"

dependencies:
  - base
  - vulkan
  - vulkan-utils
  - VulkanMemoryAllocator
  - bytestring
  - text
  - vector
  - sdl2
  - managed
  - mtl
  - extra
  - transformers
  - dear-imgui
  - geomancy
  - JuicyPixels
  - storable-record
  - inline-c
  - inline-c-cpp
  - containers
  - lens
  - lens-tutorial

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wambiguous-fields
  - -Wno-name-shadowing
  - -optl-Wl,-rpath,/usr/local/lib

executables:
  vulkan2dengine:
    main: Main.hs
    source-dirs: app