name: ashkan
version: 0.1.0.0
maintainer: "ashkan.kh.nazary@gmail.com"

dependencies:
  - base >= 4.7 && < 5
  - vulkan
  - vulkan-utils
  - bytestring
  - vector
  - sdl2
  - managed
  - mtl
  - extra
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wambiguous-fields
  # - -dynamic
  # - -dynload deploy
  # - -optl-Wl,-rpath,'$ORIGIN'
  - -optl-Wl,-rpath,/usr/local/lib
# - -optl

# library:
#   source-dirs: src

executables:
  ashkan:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N