resolver: lts-22.44 # 9.6.7

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
  - .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#
# extra-deps: []

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of Stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.11"
#
# Override the architecture used by Stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by Stack for building
# extra-include-dirs:
  # - /Users/A.Nazary/VulkanSDK/1.4.313.1/macOS/include
# extra-lib-dirs:
  # - /Users/A.Nazary/VulkanSDK/1.4.313.1/macOS/lib
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

# extra-source-files123123:
# - imgui/*.h
# - imgui/backends/*.h
# - imgui/backends/*.mm
# - imgui/imconfig.h

extra-deps:
  - vulkan-3.26.1
  # - vulkan-utils-0.5.10.6
  - VulkanMemoryAllocator-0.11.0.1
  # - dear-imgui-2.2.0
  - geomancy-0.2.6.0
  - gl-block-1.0 # geomancy
  - ptrdiff-0 # geomancy

# build:
#   executable-profiling: true  

# flags:
#   dear-imgui:
#     vulkan: true
#     sdl: true
#     opengl2: false
#     opengl3: false
#     glfw: false
